# -*- coding: utf-8 -*-
"""DataMiningTests

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BH6kvJRIZChqxJRi4MvD5ox0eTOhlQDL
"""

import requests
import io
import numpy
from bs4 import BeautifulSoup
import pandas as pd
from tabulate import tabulate
from typing import Tuple, List
import re
from datetime import datetime

def get_soup(url: str) -> BeautifulSoup:
    response = requests.get(url)
    return BeautifulSoup(response.content, 'html.parser')

def get_csv_from_url(url:str) -> pd.DataFrame:
    s=requests.get(url).content
    return pd.read_csv(io.StringIO(s.decode('utf-8')))

def print_tabulate(df: pd.DataFrame):
    print(tabulate(df, headers=df.columns, tablefmt='orgtbl'))


df = get_csv_from_url("https://raw.githubusercontent.com/JesusCab/Data-Mining-Python/main/Car_Prices_Poland_Kaggle.csv")
df.head(500)

price_table = df["price"]
price_table

gender_frame = pd.DataFrame(data=df['model'])
gender_frame

gender_frame = pd.DataFrame(data=df['price'])
gender_frame 
x=max(price_table)
y=min(price_table)
z= df["price"].mean()
w=df["price"].median()
m = df["price"].mode()
r=df["price"].count()
s=df["price"].sum()
k=df["price"].kurtosis()
v=df["price"].var()
d=df["price"].std()
print("Max {0}\n Min {1}\n Promedio {2}\n Mediana {3}\n moda {4}\n Conteo {5}\n Suma {6}\n Kutosis {7}\n Varianza {8}\n Desviacion Estandar {9}\n".format(x,y,z,w,m,r,s,k,v,d))

g = df.groupby(['model','mark']).mean()
g

df.describe()
df.info()